FROM golang:1.18-rc-alpine AS builder

#RUN apk add --no-cache vim

WORKDIR /app

COPY . .

RUN go mod init bar

RUN go mod tidy

RUN go build -o main

### 多階段建構
FROM alpine:3.15.0-rc.4

WORKDIR /app

COPY --from=builder /app/main .

EXPOSE 8080

ENTRYPOINT ["./main"]